# Generated by Django 3.2.16 on 2023-01-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0003_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
