# Generated by Django 3.2.16 on 2023-01-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0004_alter_complaint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ticket_code',
            field=models.CharField(default='', max_length=32),
        ),
    ]
