# Generated by Django 3.2.16 on 2023-01-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0006_alter_complaint_ticket_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
