# Generated by Django 3.2.16 on 2023-01-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0007_complaint_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tech_quota',
            field=models.IntegerField(default=3),
        ),
    ]
