# Generated by Django 3.2.16 on 2023-01-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0008_complaint_tech_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
