# Generated by Django 3.2.16 on 2023-01-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0010_complaint_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
