# Generated by Django 3.2.16 on 2023-01-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0011_alter_complaint_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tech_quota',
            field=models.IntegerField(default=3, verbose_name='Jumlah teknisi yang di butuhkan'),
        ),
    ]
