# Generated by Django 3.2.16 on 2023-01-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0012_auto_20230110_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='price',
        ),
        migrations.AddField(
            model_name='complaint',
            name='ground_price',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='stock_price',
            field=models.IntegerField(blank=True, default=30000, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tech_price',
            field=models.IntegerField(blank=True, default=20000, max_length=255, null=True),
        ),
    ]
