# Generated by Django 3.2.16 on 2023-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0013_auto_20230112_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='total_price',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
