# Generated by Django 3.2.16 on 2023-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0014_complaint_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ground_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='stock_price',
            field=models.IntegerField(blank=True, default=30000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tech_price',
            field=models.IntegerField(blank=True, default=20000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
