# Generated by Django 3.2.16 on 2023-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0015_auto_20230113_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
