# Generated by Django 3.2.16 on 2023-01-14 16:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0016_complaint_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='messages',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
