# Generated by Django 3.2.16 on 2023-01-14 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0017_alter_complaint_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
