# Generated by Django 3.2.16 on 2023-01-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0019_joinus'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
