# Generated by Django 3.2.16 on 2023-01-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0021_joinus_sended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinus',
            old_name='sended',
            new_name='sent',
        ),
    ]
