# Generated by Django 3.2.16 on 2023-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0022_rename_sended_joinus_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='code',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
