# Generated by Django 3.2.16 on 2023-01-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0023_joinus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
