# Generated by Django 3.2.16 on 2023-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0024_joinus_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
