# Generated by Django 3.2.16 on 2023-01-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0025_complaint_is_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='is_paid',
        ),
    ]
