# Generated by Django 3.2.16 on 2023-01-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_cs',
            field=models.BooleanField(default=False),
        ),
    ]
