# Generated by Django 3.2.16 on 2023-01-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_side', '0012_auto_20230110_0014'),
        ('company', '0006_technicianjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', related_query_name='job', to='client_side.complaint'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nik',
            field=models.CharField(max_length=20, verbose_name='NIK KTP (Dirahasiakan)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wa_number',
            field=models.CharField(max_length=255, verbose_name='Nomor Whatsapp yang bisa di hubungi'),
        ),
        migrations.CreateModel(
            name='GroundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report/', verbose_name='upload file bukti lapangan')),
                ('case', models.TextField(verbose_name='laporkan kasus yang terjadi di lapangan')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_report', related_query_name='job_report', to='client_side.complaint')),
            ],
        ),
    ]
