# Generated by Django 3.2.16 on 2023-01-12 06:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20230112_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundreport',
            name='case',
            field=ckeditor.fields.RichTextField(verbose_name='laporkan kasus yang terjadi di lapangan'),
        ),
    ]
