# Generated by Django 3.2.16 on 2023-01-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_groundreport_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proof',
        ),
    ]
